/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab2_gabriel_alvarado;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel Alvarado
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ppmenu = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        ppm2 = new javax.swing.JPopupMenu();
        mod = new javax.swing.JMenuItem();
        eliminate = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nombrep = new javax.swing.JTextField();
        tf_tempep = new javax.swing.JTextField();
        tf_superficie = new javax.swing.JTextField();
        tf_distancia = new javax.swing.JTextField();
        tf_anillosi = new javax.swing.JRadioButton();
        tf_anillosno = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Nacionalidad = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombrep1 = new javax.swing.JTextField();
        tf_nacionalidad = new javax.swing.JTextField();
        tf_sueldo = new javax.swing.JTextField();
        cb_experiencia = new javax.swing.JComboBox();
        tf_sexo = new javax.swing.JRadioButton();
        bt_femenino = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_serie = new javax.swing.JTextField();
        cb_destinos = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        tf_velocidad1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cb_astronautas = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        tf_serie1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cb_destinos1 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        tf_velocidad = new javax.swing.JTextField();
        cb_despeje = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_material = new javax.swing.JTextField();
        tf_peso2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        tf_serie2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cb_destinos2 = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        cb_astronautas2 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        tf_pos2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_pos = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        cb_planetas2 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        tf_pos1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        ppmenu.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        ppmenu.add(Eliminar);

        mod.setText("modificar");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        ppm2.add(mod);

        eliminate.setText("eliminar");
        ppm2.add(eliminate);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Planetas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel3.setText("Temperatura");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel4.setText("Anillos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel5.setText("Tipo de superficie");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel6.setText("Distancia");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));
        jPanel1.add(tf_nombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, -1));
        jPanel1.add(tf_tempep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 200, -1));
        jPanel1.add(tf_superficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 200, 20));
        jPanel1.add(tf_distancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 200, -1));

        tf_anillosi.setText("Si");
        jPanel1.add(tf_anillosi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        tf_anillosno.setText("No");
        jPanel1.add(tf_anillosno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jTabbedPane1.addTab("Planetas", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Astronautas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel8.setText("Nombre");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        Nacionalidad.setText("Temperatura");
        jPanel2.add(Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel10.setText("Sueldo");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel11.setText("Experiencia");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel12.setText("sexo");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
        jPanel2.add(tf_nombrep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, -1));
        jPanel2.add(tf_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 200, -1));
        jPanel2.add(tf_sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 200, -1));

        cb_experiencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Explorador", "Medico", "Ingeniero", " ", " " }));
        jPanel2.add(cb_experiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, -1));

        tf_sexo.setText("Masculino");
        jPanel2.add(tf_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 80, -1));

        bt_femenino.setText("Femenino");
        bt_femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_femeninoActionPerformed(evt);
            }
        });
        jPanel2.add(bt_femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 90, -1));

        jLabel9.setText("Peso");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));
        jPanel2.add(tf_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 190, -1));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jTabbedPane1.addTab("Astronautas", jPanel2);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Nave Espacial");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 45, -1, -1));

        jLabel14.setText("numero serie");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 108, -1, -1));

        jLabel15.setText("planeta destino");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 213, -1, -1));
        jPanel4.add(tf_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, -1));

        jPanel4.add(cb_destinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 210, -1));

        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel25.setText("Velocidad");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        jPanel4.add(tf_velocidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 190, -1));

        jTabbedPane2.addTab("Nave espacial", jPanel4);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("Nave Tripulada");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel17.setText("Lugar de inicio");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jButton4.setText("Registrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jLabel21.setText("Elija un astronauta");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jPanel6.add(cb_astronautas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 146, -1));

        jLabel23.setText("numero serie");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 80, 10));
        jPanel6.add(tf_serie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 200, 20));

        jLabel24.setText("planeta destino");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 10));

        jPanel6.add(cb_destinos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 210, 20));

        jLabel22.setText("Velocidad");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 124, 60, 10));
        jPanel6.add(tf_velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 200, -1));

        jPanel6.add(cb_despeje, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 210, -1));

        jTabbedPane2.addTab("nave tripulada", jPanel6);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Sonda Espacial");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel19.setText("Material");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel20.setText("Peso");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 38, -1));
        jPanel5.add(tf_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 178, -1));
        jPanel5.add(tf_peso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 178, -1));

        jButton5.setText("Registrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 327, -1, -1));

        jLabel27.setText("numero serie");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 10));
        jPanel5.add(tf_serie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, 20));

        jLabel28.setText("planeta destino");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 10));

        jPanel5.add(cb_destinos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 20));

        jTabbedPane2.addTab("Sonda espacial", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Naves espaciales", jPanel3);

        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.add(cb_astronautas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 77, 130, -1));

        jLabel26.setText("Astronautas");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 44, -1, -1));

        jButton6.setText("Cargar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 76, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Sueldo", "experiencia", "sexo", "peso"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 193, 358, 96));

        jButton7.setText("Agregar a tabla");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 152, -1, -1));

        jLabel29.setText("Ingrese pos");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 124, -1, -1));

        tf_pos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pos2ActionPerformed(evt);
            }
        });
        jPanel7.add(tf_pos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 121, 91, -1));

        jLabel30.setText("Ingrese posicion a modificar o eliminar");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));
        jPanel7.add(tf_pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 110, -1));

        jButton11.setText("Cargar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jTabbedPane1.addTab("Listar Astronautas", jPanel7);

        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("Planetas");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 44, -1, -1));

        cb_planetas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_planetas2ActionPerformed(evt);
            }
        });
        jPanel8.add(cb_planetas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 77, 130, -1));

        jButton8.setText("Cargar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 76, -1, -1));

        jLabel32.setText("Ingrese pos");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 124, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 121, 91, -1));

        jButton9.setText("Agregar a tabla");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 152, -1, -1));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Temperatura", "Anillos", "tipo", "sexo"
            }
        ));
        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla1);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 193, 358, 96));

        jLabel33.setText("Ingrese posicion a modificar o eliminar");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        tf_pos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pos1ActionPerformed(evt);
            }
        });
        jPanel8.add(tf_pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 110, -1));

        jButton10.setText("Cargar Tabla");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jTabbedPane1.addTab("Listar planetas", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel9);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_femeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_femeninoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre;
        int temperatura;
        String anillos = "";
        String tipo;
        int distancia;
        nombre = tf_nombrep.getText();
        temperatura = Integer.parseInt(tf_tempep.getText());
        if (tf_anillosi.isSelected()) {
            anillos = "si";
        } else {

            anillos = "no";
        }

        tipo = tf_superficie.getText();
        distancia = Integer.parseInt(tf_distancia.getText());
        ListPlanetas.add(new Planetas(nombre, temperatura, anillos, tipo, distancia));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre;
        String nacionalidad;
        String sueldo;
        String experiencia;
        int peso;
        String sexo;
        nombre = tf_nombrep1.getText();
        nacionalidad = tf_nacionalidad.getText();
        sueldo = tf_sueldo.getText();
        experiencia = cb_experiencia.getSelectedItem().toString();
        peso = Integer.parseInt(tf_peso.getText());
        if (tf_sexo.isSelected()) {
            sexo = "masculino";
        } else {
            sexo = "mujer";
        }
        ListAstronauta.add(new Astronautas(nombre, nacionalidad, sueldo, experiencia, sexo, peso));

        //
        tf_nombrep1.setText("");
        tf_nacionalidad.setText("");
        tf_sueldo.setText("");
        tf_peso.setText("");


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Planetas lugar;
        String serie;
        Planetas Destino;
        Astronautas nombre;
        int velocidad;

       lugar = (Planetas) cb_despeje.getSelectedItem();
        nombre = (Astronautas) cb_astronautas.getSelectedItem();
        Destino = (Planetas) cb_destinos.getSelectedItem();
        serie = tf_serie1.getText();
        velocidad = Integer.parseInt(tf_velocidad.getText());
        ListNaves.add(new NaveTripulada(lugar, serie, Destino, velocidad));

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String serie;
        Planetas destino;
        int velocidad;
        serie = tf_serie.getText();
        destino = (Planetas) cb_destinos1.getSelectedItem();
        velocidad = Integer.parseInt(tf_velocidad1.getText());
        ListNaves.add(new NavesEspaciales(serie, destino, velocidad));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String serie;
        Planetas destino;
        int velocidad;
        String material;
        int peso;
        serie = tf_serie2.getText();
        destino = (Planetas) cb_destinos2.getSelectedItem();
        velocidad = Integer.parseInt(tf_velocidad.getText());
        material = tf_material.getText();
        peso = Integer.parseInt(tf_peso2.getText());
        ListNaves.add(new SondaEspacial(material, peso, serie, destino, velocidad));


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_astronautas2.getModel();
        DefaultComboBoxModel model2 = (DefaultComboBoxModel)cb_astronautas.getModel();
        for (Astronautas t : ListAstronauta) {
            model.addElement(t);
            model2.addElement(t);
        }
        cb_astronautas2.setModel(model);
        cb_astronautas.setModel(model2);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        if (evt.isMetaDown()) {
            this.ppmenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

    }//GEN-LAST:event_tablaMouseClicked

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        int i = Integer.parseInt(tf_pos.getText());
        String nombre;
        String nacionalidad;
        String sueldo;
        String experiencia;
        int peso;
        String sexo;
        nombre = JOptionPane.showInputDialog("Ingrese nombre");
        nacionalidad = JOptionPane.showInputDialog("Ingrese nacionaldiad");
        sueldo = JOptionPane.showInputDialog("Ingrese sueldo");
        sexo = JOptionPane.showInputDialog("Ingrese sueldo");
        peso = Integer.parseInt(JOptionPane.showInputDialog("Ingrese sueldo"));
        experiencia = JOptionPane.showInputDialog("Ingrese experiencia");
        ListAstronauta.get(i).setNombre(nombre);
        ListAstronauta.get(i).setNacionalidad(nacionalidad);
        ListAstronauta.get(i).setPeso(peso);
        ListAstronauta.get(i).setSexo(sexo);
        ListAstronauta.get(i).setExperiencia(experiencia);
        ListAstronauta.get(i).setSueldo(sueldo);


    }//GEN-LAST:event_ModificarActionPerformed

    private void tf_pos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pos2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Astronautas a = ListAstronauta.get(cb_astronautas2.getSelectedIndex());
        Object[] row = {a.getNombre(), a.getNacionalidad(), a.getSueldo(), a.getExperiencia(), a.getSexo(), a.getPeso()};
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        model.addRow(row);
        tabla.setModel(model);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_planetas2.getModel();
        DefaultComboBoxModel model2  = (DefaultComboBoxModel)cb_despeje.getModel();
       
        for (Planetas t : ListPlanetas) {
            model.addElement(t);
            model2.addElement(t);
        }
        cb_planetas2.setModel(model);
        cb_despeje.setModel(model2);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Planetas a = ListPlanetas.get(cb_planetas2.getSelectedIndex());
        Object[] row = {a.getNombre(), a.getTemperatura(), a.getAnillos(), a.getTipoSuperficie(), a.getDistancia()};
        DefaultTableModel model = (DefaultTableModel) tabla1.getModel();
        model.addRow(row);
        tabla1.setModel(model);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla1MouseClicked

    private void cb_planetas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_planetas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_planetas2ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        try {

            //int pos = Integer.parseInt(tf_pos.getText());
            if (cb_astronautas2.getSelectedIndex() >= 0) {
                DefaultComboBoxModel model = (DefaultComboBoxModel) cb_astronautas2.getModel();
                model.removeElementAt(cb_astronautas2.getSelectedIndex());
                cb_astronautas2.setModel(model);

            }
            if (tabla.getSelectedRow() >= 0) {
                DefaultTableModel model = (DefaultTableModel) tabla1.getModel();
                model.removeRow(tabla1.getSelectedRow());
                tabla.setModel(model);
            }
            for (Astronautas g : ListAstronauta) {

                if (cb_planetas2.getSelectedItem().toString().equals(g.getNombre())) {
                    ListAstronauta.remove(g);

                }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        if (evt.isMetaDown()) {
            ppm2.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jPanel8MouseClicked

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        int i = Integer.parseInt(tf_pos1.getText());
        String nombre;
        int temperatura;
        String anillos = "";
        String tipo;
        int distancia;

        nombre = JOptionPane.showInputDialog("ingrese el nombre");
        temperatura = Integer.parseInt(JOptionPane.showInputDialog("ingrese la temperatura"));
        anillos = JOptionPane.showInputDialog("ingrese si tiene anillos");
        tipo = JOptionPane.showInputDialog("ingrese el tipo");
        distancia = Integer.parseInt(JOptionPane.showInputDialog("ingrese la distancia"));
        ListPlanetas.get(i).setDistancia(distancia);
        ListPlanetas.get(i).setTemperatura(temperatura);
        ListPlanetas.get(i).setNombre(nombre);
        ListPlanetas.get(i).setAnillos(anillos);
        ListPlanetas.get(i).setTipoSuperficie(tipo);


    }//GEN-LAST:event_modActionPerformed

    private void tf_pos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pos1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();

        Astronautas a = ListAstronauta.get(cb_astronautas2.getSelectedIndex());
        int fila = tabla.getSelectedRow();
        Object[] row = {a.getNombre(), a.getNacionalidad(), a.getSueldo(), a.getExperiencia(), a.getSexo(), a.getPeso()};
        int i = tabla1.getSelectedRow();
        model.removeRow(fila);
        model.addRow(row);
        tabla.setModel(model);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabla1.getModel();

        Planetas a = ListPlanetas.get(cb_planetas2.getSelectedIndex());
        int fila = tabla1.getSelectedRow();
        Object[] row = {a.getNombre(), a.getTemperatura(), a.getAnillos(), a.getTipoSuperficie(), a.getDistancia()};
        int i = tabla1.getSelectedRow();
        model.removeRow(fila);
        model.addRow(row);
        tabla1.setModel(model);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JLabel Nacionalidad;
    private javax.swing.JRadioButton bt_femenino;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb_astronautas;
    private javax.swing.JComboBox cb_astronautas2;
    private javax.swing.JComboBox cb_despeje;
    private javax.swing.JComboBox cb_destinos;
    private javax.swing.JComboBox cb_destinos1;
    private javax.swing.JComboBox cb_destinos2;
    private javax.swing.JComboBox cb_experiencia;
    private javax.swing.JComboBox cb_planetas2;
    private javax.swing.JMenuItem eliminate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuItem mod;
    private javax.swing.JPopupMenu ppm2;
    private javax.swing.JPopupMenu ppmenu;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tabla1;
    private javax.swing.JRadioButton tf_anillosi;
    private javax.swing.JRadioButton tf_anillosno;
    private javax.swing.JTextField tf_distancia;
    private javax.swing.JTextField tf_material;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nombrep;
    private javax.swing.JTextField tf_nombrep1;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_peso2;
    private javax.swing.JTextField tf_pos;
    private javax.swing.JTextField tf_pos1;
    private javax.swing.JTextField tf_pos2;
    private javax.swing.JTextField tf_serie;
    private javax.swing.JTextField tf_serie1;
    private javax.swing.JTextField tf_serie2;
    private javax.swing.JRadioButton tf_sexo;
    private javax.swing.JTextField tf_sueldo;
    private javax.swing.JTextField tf_superficie;
    private javax.swing.JTextField tf_tempep;
    private javax.swing.JTextField tf_velocidad;
    private javax.swing.JTextField tf_velocidad1;
    // End of variables declaration//GEN-END:variables
ArrayList<Astronautas> ListAstronauta = new ArrayList();
    ArrayList<Planetas> ListPlanetas = new ArrayList();
    ArrayList<NavesEspaciales> ListNaves = new ArrayList();

}
